#!/usr/bin/env bash
# Writes src/sets/fonts/numerals-data.js (base64 woff2 of Cinzel Bold subset to 0-9 and ?)
# and src/sets/fonts/OFL.txt (the font's licence). Google Fonts serves a static weight-700
# subset when asked with text=; we embed exactly that file. Re-run to refresh.
set -euo pipefail
cd "$(dirname "$0")/.."

UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
CSS_URL='https://fonts.googleapis.com/css2?family=Cinzel:wght@700&text=0123456789%3F&display=swap'
LICENCE_URL='https://raw.githubusercontent.com/google/fonts/main/ofl/cinzel/OFL.txt'

CSS=$(curl -sf -A "$UA" "$CSS_URL")
URL=$(printf '%s' "$CSS" | sed -n 's/.*url(\([^)]*\)) format(.woff2.).*/\1/p' | head -1)
if [ -z "$URL" ]; then echo "could not find a woff2 url in the Google Fonts CSS" >&2; exit 1; fi

TMP=$(mktemp)
curl -sf -A "$UA" "$URL" -o "$TMP"
MAGIC=$(head -c 4 "$TMP")
if [ "$MAGIC" != "wOF2" ]; then echo "downloaded file is not woff2" >&2; exit 1; fi

B64=$(base64 < "$TMP" | tr -d '\n')
mkdir -p src/sets/fonts
{
  echo "// Generated by scripts/subset-font.sh. Do not edit by hand."
  echo "// Cinzel Bold (SIL Open Font License 1.1, see OFL.txt), subset to the digits 0-9 and '?', woff2."
  echo "export const NUMERAL_FONT_WOFF2_BASE64 = '$B64';"
} > src/sets/fonts/numerals-data.js
curl -sf "$LICENCE_URL" -o src/sets/fonts/OFL.txt
echo "wrote src/sets/fonts/numerals-data.js ($(wc -c < "$TMP" | tr -d ' ') bytes of woff2) and src/sets/fonts/OFL.txt"
rm -f "$TMP"
