#!/usr/bin/env bash
# Writes src/sets/fonts/numerals-data.js: a map of embedded family name -> base64 woff2 of
# that font subset to the digits 0-9 and '?', plus each font's SIL OFL licence text.
# Google Fonts serves a static subset when asked with text=; we embed exactly that file.
#
# Every built-in family below is written on each run; pass extra families as triples of
#   FAMILY GOOGLE_NAME ALIAS
# where FAMILY is the css2 family spec (e.g. 'Cinzel:wght@700'), GOOGLE_NAME the directory
# under google/fonts/ofl (e.g. 'cinzel') and ALIAS the neutral family name the engine
# registers it under (never the font's own, possibly reserved, name). Extra licences land in
# src/sets/fonts/OFL-<family-kebab>.txt. Re-run to refresh.
set -euo pipefail
cd "$(dirname "$0")/.."

UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
TEXT='0123456789%3F'
OUT=src/sets/fonts/numerals-data.js

# FAMILY|GOOGLE_NAME|ALIAS|LICENCE_FILE
FONTS=(
  'Cinzel:wght@700|cinzel|OpenDiceNumerals|OFL.txt'
  'Share+Tech+Mono|sharetechmono|OpenDiceMono|OFL-share-tech-mono.txt'
)
if [ $(( $# % 3 )) -ne 0 ]; then echo "usage: $0 [FAMILY GOOGLE_NAME ALIAS]..." >&2; exit 2; fi
while [ $# -ge 3 ]; do
  KEBAB=$(printf '%s' "$1" | sed 's/:.*//' | tr '+ ' '--' | tr '[:upper:]' '[:lower:]')
  FONTS+=("$1|$2|$3|OFL-$KEBAB.txt")
  shift 3
done

TMP=$(mktemp)
mkdir -p src/sets/fonts
{
  echo "// Generated by scripts/subset-font.sh. Do not edit by hand."
  echo "// Each family is subset to the digits 0-9 and '?', woff2, SIL Open Font License 1.1 (see the OFL*.txt beside this file)."
  echo "export const NUMERAL_FONT_DATA = {"
} > "$OUT.tmp"

for ENTRY in "${FONTS[@]}"; do
  IFS='|' read -r FAMILY GOOGLE_NAME ALIAS LICENCE_FILE <<< "$ENTRY"
  CSS_URL="https://fonts.googleapis.com/css2?family=${FAMILY}&text=${TEXT}&display=swap"
  LICENCE_URL="https://raw.githubusercontent.com/google/fonts/main/ofl/${GOOGLE_NAME}/OFL.txt"

  CSS=$(curl -sf -A "$UA" "$CSS_URL")
  URL=$(printf '%s' "$CSS" | sed -n 's/.*url(\([^)]*\)) format(.woff2.).*/\1/p' | head -1)
  if [ -z "$URL" ]; then echo "$FAMILY: could not find a woff2 url in the Google Fonts CSS" >&2; exit 1; fi

  curl -sf -A "$UA" "$URL" -o "$TMP"
  MAGIC=$(head -c 4 "$TMP")
  if [ "$MAGIC" != "wOF2" ]; then echo "$FAMILY: downloaded file is not woff2" >&2; exit 1; fi

  B64=$(base64 < "$TMP" | tr -d '\n')
  HUMAN=$(printf '%s' "$FAMILY" | sed 's/:.*//' | tr '+' ' ')
  {
    echo "    // $HUMAN, licence in $LICENCE_FILE"
    echo "    $ALIAS: '$B64',"
  } >> "$OUT.tmp"
  curl -sf "$LICENCE_URL" -o "src/sets/fonts/$LICENCE_FILE"
  echo "$ALIAS: $(wc -c < "$TMP" | tr -d ' ') bytes of woff2 ($HUMAN), licence src/sets/fonts/$LICENCE_FILE"
done

echo "};" >> "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
rm -f "$TMP"
echo "wrote $OUT"
